CREATE DATABASE MMO_LJ;

USE MMO_LJ;

CREATE TABLE MMCLIENTE(
CODCLI INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(100)NOT NULL,
EMAIL VARCHAR(255) UNIQUE,
TELEFONE VARCHAR(20),
DATANASC DATE,
DATACADASTRO DATETIME default CURRENT_TIMESTAMP,
DATAULTCOMP DATETIME DEFAULT CURRENT_TIMESTAMP,
ENDERECO VARCHAR(255),
BAIRRO VARCHAR(255),
CEP VARCHAR(20));
