##cRIACAO DE TRIGGER DE ATT AUTOMATICA DE ULTIMA COMPRA

DELIMITER//
CREATE TRIGGER MMOAtualiza_data_ultima_compra AFTER INSERT ON MMPEDC
FOR EACH ROW
BEGIN
	UPDATE MMCLIENTE
    SET DATAULTCOMP = NOW ()
    WHERE MMCLIENT.CODCLI = NEW.CODCLI;
END;

//DELIMITER;
